### ISSUE TITLE
Make Wubb juice Wubb again

### ISSUE THREAD

**Issue by MrSelenix** [m1jordanallen/1.19OceanSurvival#37] opened 2023-08-05 22:22 UTC
Wubb Wubb Wubb Wubb Wubb

(enable force liquid regen in configs)
I think i was in 0.0.6. force liquid applied regen effect, but wasnt actually healing the player. Also no screen shake

**Comment by ka13btv** [comment] 2023-08-06 11:58
Potential duplicate of #34

**Comment by m1jordanallen** [comment] 2023-08-09 13:06
Regen 1 is really weak with the health tweaks we make

**Closed as completed by m1jordanallen** 2023-08-09 13:06 UTC

**Comment by MrSelenix** [comment] 2023-08-09 13:44
I mean, "weak" is an understatement, spent like 5 minutes in the juice and didnt even gain half a heart :D

**Comment by m1jordanallen** [comment] 2023-08-09 13:49
when I tested it, I was getting about half a heart every 10 seconds or so.......

IDK man, but when I tested it in the upcoming build, it seems to be working.

Im not really that worried about it regardless.
